// data-vocab.js
// Contiene todos los temas de vocabulario interactivo

const vocabTopics = [
  {
    id:'colors', title:'Los Colores', icon:'🎨', count:14,
    words:[
      {en:'black',es:'negro/a',example:'The cat is black. / The sky is black at night.'},
      {en:'white',es:'blanco/a',example:'Snow is white. / She is wearing a white dress.'},
      {en:'red',es:'rojo/a',example:'The apple is red. / He drives a red car.'},
      {en:'blue',es:'azul',example:'The sky is blue. / She has blue eyes.'},
      {en:'green',es:'verde',example:'The grass is green. / I like green vegetables.'},
      {en:'yellow',es:'amarillo/a',example:'The sun is yellow. / He wears a yellow hat.'},
      {en:'orange',es:'naranja',example:'The fruit is orange. / She painted the wall orange.'},
      {en:'purple',es:'morado/a / violeta',example:'The flower is purple. / She likes purple clothes.'},
      {en:'pink',es:'rosa',example:'The sky is pink at sunset. / She has a pink bag.'},
      {en:'brown',es:'marrón / café',example:'The dog is brown. / He has brown hair.'},
      {en:'grey',es:'gris',example:'The sky is grey and cloudy today.'},
      {en:'navy',es:'azul marino',example:'He wears a navy blue suit to work.'},
      {en:'beige',es:'beige / crema',example:'The walls of the living room are beige.'},
      {en:'gold',es:'dorado/a',example:'She wears a beautiful gold necklace.'},
    ]
  },
  {
    id:'family', title:'La Familia', icon:'👨‍👩‍👧', count:20,
    words:[
      {en:'father',es:'padre',example:'My father is a doctor. He is 50 years old.'},
      {en:'mother',es:'madre',example:'My mother is a teacher. She loves reading.'},
      {en:'brother',es:'hermano',example:'I have one brother. His name is Luis.'},
      {en:'sister',es:'hermana',example:'My sister is older than me. She lives in Bogotá.'},
      {en:'son',es:'hijo',example:'They have two sons and one daughter.'},
      {en:'daughter',es:'hija',example:'Their daughter is studying medicine at university.'},
      {en:'grandfather',es:'abuelo',example:'My grandfather is 75 years old and retired.'},
      {en:'grandmother',es:'abuela',example:'My grandmother makes delicious arepas every Sunday.'},
      {en:'uncle',es:'tío',example:'My uncle lives in Canada. He visits us in summer.'},
      {en:'aunt',es:'tía',example:'My aunt has three children. They are lovely.'},
      {en:'cousin',es:'primo/a',example:'My cousin and I are the same age.'},
      {en:'husband',es:'esposo / marido',example:'Her husband is very kind and funny.'},
      {en:'wife',es:'esposa',example:'His wife is a lawyer. She works very hard.'},
      {en:'nephew',es:'sobrino',example:'My nephew is only three years old.'},
      {en:'niece',es:'sobrina',example:'My niece loves dancing and music.'},
      {en:'twins',es:'gemelos/as',example:'My cousins are twins. They look identical!'},
      {en:'parents',es:'padres',example:'My parents are from Cali, Colombia.'},
      {en:'grandparents',es:'abuelos',example:'My grandparents live near us in the same street.'},
      {en:'stepfather',es:'padrastro',example:'Her stepfather is very friendly and kind.'},
      {en:'stepmother',es:'madrastra',example:'His stepmother is a nurse at the hospital.'},
    ]
  },
  {
    id:'people', title:'Las Personas', icon:'👤', count:16,
    words:[
      {en:'baby',es:'bebé',example:'The baby is sleeping. She is only six months old.'},
      {en:'toddler',es:'niño/a pequeño/a (1-3 años)',example:'The toddler is learning to walk.'},
      {en:'child',es:'niño/a',example:'The child is playing in the park.'},
      {en:'teenager',es:'adolescente',example:'She is a teenager. She is fifteen years old.'},
      {en:'young person',es:'joven',example:'He is a young person full of energy and ideas.'},
      {en:'adult',es:'adulto/a',example:'Adults pay full price at the cinema.'},
      {en:'middle-aged',es:'de mediana edad',example:'He is middle-aged, about forty-five years old.'},
      {en:'elderly',es:'anciano/a / mayor',example:'The elderly man reads the newspaper every morning.'},
      {en:'woman',es:'mujer',example:'The woman in the red coat is my English teacher.'},
      {en:'man',es:'hombre',example:'The man at the door is waiting for you.'},
      {en:'girl',es:'chica / niña',example:'The girl has long blonde hair and blue eyes.'},
      {en:'boy',es:'chico / niño',example:'The boy runs very fast in the park.'},
      {en:'lady',es:'señora / dama',example:'The lady at reception is very helpful.'},
      {en:'gentleman',es:'caballero / señor',example:'The gentleman opened the door for her.'},
      {en:'person',es:'persona',example:'There is one person in the room.'},
      {en:'people',es:'personas / gente',example:'There are many people in the street today.'},
    ]
  },
  {
    id:'greetings', title:'Saludos y Presentaciones', icon:'👋', count:18,
    words:[
      {en:'Good morning',es:'Buenos días',example:'Good morning! How are you today?'},
      {en:'Good afternoon',es:'Buenas tardes',example:'Good afternoon, Mrs Smith. How are you?'},
      {en:'Good evening',es:'Buenas noches (al llegar)',example:'Good evening, ladies and gentlemen!'},
      {en:'Good night',es:'Buenas noches (al despedirse)',example:'Good night! Sleep well!'},
      {en:'Hello / Hi',es:'Hola',example:'"Hello!" / "Hi, how\'s it going?"'},
      {en:'Goodbye / Bye',es:'Adiós',example:'"Goodbye, see you tomorrow!"'},
      {en:'See you later',es:'Hasta luego',example:'"See you later, have a great day!"'},
      {en:'See you tomorrow',es:'Hasta mañana',example:'"See you tomorrow at school!"'},
      {en:'How are you?',es:'¿Cómo estás?',example:'"Hi Tom! How are you?" "Fine, thanks!"'},
      {en:'Fine, thanks',es:'Bien, gracias',example:'"How are you?" — "Fine, thanks. And you?"'},
      {en:'Not bad',es:'No me quejo / Bastante bien',example:'"How are you?" — "Not bad, thanks."'},
      {en:"What's your name?",es:'¿Cómo te llamas?',example:'"What\'s your name?" "My name is Ana."'},
      {en:'My name is...',es:'Me llamo... / Mi nombre es...',example:'"My name is Carlos. Nice to meet you!"'},
      {en:'Nice to meet you',es:'Mucho gusto / Encantado/a',example:'"Nice to meet you, Ana!" "Nice to meet you too!"'},
      {en:'Where are you from?',es:'¿De dónde eres?',example:'"Where are you from?" "I\'m from Colombia."'},
      {en:"I'm from...",es:'Soy de...',example:'"I\'m from Cúcuta, in the north of Colombia."'},
      {en:'How old are you?',es:'¿Cuántos años tienes?',example:'"How old are you?" "I\'m 22 years old."'},
      {en:'Best wishes',es:'Mis mejores deseos',example:'"Best wishes to your family!" "Thank you so much!"'},
    ]
  },
  {
    id:'numbers_vocab', title:'Números y Fechas', icon:'🔢', count:18,
    words:[
      {en:'one / first',es:'uno / primero',example:'"I have one dog." / "She is first in class."'},
      {en:'two / second',es:'dos / segundo',example:'"I need two tickets." / "He came second."'},
      {en:'three / third',es:'tres / tercero',example:'"There are three rooms." / "This is the third time."'},
      {en:'five / fifth',es:'cinco / quinto',example:'"I have five friends." / "She lives on the fifth floor."'},
      {en:'ten / tenth',es:'diez / décimo',example:'"There are ten students." / "Today is the tenth of March."'},
      {en:'twelve / twelfth',es:'doce / duodécimo',example:'"Twelve months in a year." / "December is the twelfth month."'},
      {en:'fifteen / fifteenth',es:'quince / decimoquinto',example:'"She is fifteen years old." / "On the fifteenth of June."'},
      {en:'twenty / twentieth',es:'veinte / vigésimo',example:'"I need twenty minutes." / "The twentieth century."'},
      {en:'thirty / thirtieth',es:'treinta / trigésimo',example:'"He is thirty years old." / "On the thirtieth of April."'},
      {en:'forty / fortieth',es:'cuarenta / cuadragésimo',example:'"There are forty students." ⚠️ forty (NO fourty!)'},
      {en:'fifty / fiftieth',es:'cincuenta / quincuagésimo',example:'"Fifty people attended." / "Her fiftieth birthday."'},
      {en:'a hundred',es:'cien / ciento',example:'"There are a hundred people in the room."'},
      {en:'a thousand',es:'mil',example:'"A thousand students study here."'},
      {en:'a million',es:'un millón',example:'"One million people live in this city."'},
      {en:'half',es:'medio/a / la mitad',example:'"Half past seven." / "I want half, please."'},
      {en:'quarter',es:'un cuarto',example:'"A quarter past eight." / "Quarter to nine."'},
      {en:'dozen',es:'docena',example:'"A dozen eggs, please." (= 12)'},
      {en:'couple',es:'un par / dos (aprox.)',example:'"I need a couple of minutes." (= 2 approximately)'},
    ]
  },
  {
    id:'jobs', title:'Profesiones y trabajos', icon:'💼', count:18,
    words:[
      {en:'doctor',es:'médico/a',example:'"She is a doctor. She works at the hospital."'},
      {en:'nurse',es:'enfermero/a',example:'"My aunt is a nurse. She works night shifts."'},
      {en:'teacher',es:'profesor/a / maestro/a',example:'"My father is a teacher. He teaches maths."'},
      {en:'engineer',es:'ingeniero/a',example:'"He is an engineer. He designs bridges."'},
      {en:'lawyer',es:'abogado/a',example:'"She is a lawyer and works at a big firm."'},
      {en:'police officer',es:'oficial de policía',example:'"The police officer helped the lost child."'},
      {en:'firefighter',es:'bombero/a',example:'"Firefighters are very brave people."'},
      {en:'chef',es:'chef / cocinero/a',example:'"He is a chef at a famous restaurant."'},
      {en:'journalist',es:'periodista',example:'"She is a journalist for a national newspaper."'},
      {en:'accountant',es:'contable / contador/a',example:'"He works as an accountant at a bank."'},
      {en:'architect',es:'arquitecto/a',example:'"She is an architect. She designs beautiful buildings."'},
      {en:'artist',es:'artista',example:'"He is an artist. He paints every day."'},
      {en:'musician',es:'músico/a',example:'"She is a musician. She plays the guitar."'},
      {en:'pilot',es:'piloto',example:'"He is a pilot and flies to Europe every week."'},
      {en:'farmer',es:'agricultor/a / granjero/a',example:'"My grandfather was a farmer. He had cows and chickens."'},
      {en:'student',es:'estudiante',example:'"I am a student. I study at university."'},
      {en:'businessman',es:'empresario/a',example:'"He is a successful businessman."'},
      {en:'receptionist',es:'recepcionista',example:'"The receptionist at the hotel was very helpful."'},
    ]
  },
  {
    id:'places', title:'Lugares de la ciudad', icon:'🏙️', count:18,
    words:[
      {en:'bank',es:'banco',example:'"The bank is on the corner of the street."'},
      {en:'hospital',es:'hospital',example:'"She works at the hospital near the park."'},
      {en:'school',es:'escuela / colegio',example:'"The school is next to the library."'},
      {en:'supermarket',es:'supermercado',example:'"We do the shopping at the supermarket on Saturdays."'},
      {en:"chemist's / pharmacy",es:'farmacia',example:'"I need to go to the chemist\'s for medicine."'},
      {en:'post office',es:'oficina de correos',example:'"I sent a letter at the post office yesterday."'},
      {en:'library',es:'biblioteca',example:'"I study at the library every afternoon after school."'},
      {en:'church',es:'iglesia',example:'"The church is opposite the town hall."'},
      {en:'park',es:'parque',example:'"We walk in the park on Sunday mornings."'},
      {en:'station',es:'estación (de tren/metro)',example:'"The station is behind the hotel."'},
      {en:'airport',es:'aeropuerto',example:'"Our flight leaves from the airport at noon."'},
      {en:'restaurant',es:'restaurante',example:'"We had dinner at a nice Italian restaurant."'},
      {en:'café',es:'cafetería',example:'"I meet my friends at the café on Friday evenings."'},
      {en:'cinema',es:'cine',example:'"We went to the cinema last Saturday night."'},
      {en:'museum',es:'museo',example:'"The museum is in the city centre and it\'s free."'},
      {en:'hotel',es:'hotel',example:'"The hotel is opposite the train station."'},
      {en:'market',es:'mercado',example:'"There is a big market in the square every Sunday."'},
      {en:'town hall',es:'ayuntamiento / alcaldía',example:'"The town hall is a beautiful old building in the centre."'},
    ]
  },
  {
    id:'adjectives', title:'Adjetivos esenciales', icon:'✨', count:20,
    words:[
      {en:'big / large',es:'grande',example:'"London is a big city." / "She has a large family."'},
      {en:'small / little',es:'pequeño/a',example:'"It\'s a small house but very cosy and comfortable."'},
      {en:'old',es:'viejo/a / antiguo/a / mayor',example:'"He is an old man." / "This is an old building."'},
      {en:'young',es:'joven',example:'"She is very young — only eighteen years old."'},
      {en:'new',es:'nuevo/a',example:'"I have a new computer. I love it!"'},
      {en:'good',es:'bueno/a',example:'"She is a good student. She works very hard."'},
      {en:'bad',es:'malo/a',example:'"The weather is very bad today. It\'s raining heavily."'},
      {en:'beautiful',es:'hermoso/a / precioso/a',example:'"She has a beautiful voice. Everyone loves hearing her sing."'},
      {en:'ugly',es:'feo/a',example:'"That old building is really ugly!"'},
      {en:'tall',es:'alto/a',example:'"He is very tall — almost two metres!"'},
      {en:'short',es:'bajo/a / corto/a',example:'"She is quite short, just like her mother."'},
      {en:'hot',es:'caliente / caluroso',example:'"It\'s very hot today! Let\'s go swimming."'},
      {en:'cold',es:'frío/a',example:'"The coffee is cold. Can you warm it up please?"'},
      {en:'expensive',es:'caro/a',example:'"This restaurant is too expensive for me."'},
      {en:'cheap',es:'barato/a',example:'"This market is cheap and has great fresh food."'},
      {en:'interesting',es:'interesante',example:'"The book is very interesting. I can\'t stop reading it."'},
      {en:'boring',es:'aburrido/a',example:'"The film was really boring. I almost fell asleep."'},
      {en:'kind',es:'amable / bondadoso/a',example:'"My teacher is very kind and always helps us."'},
      {en:'friendly',es:'amigable / simpático/a',example:'"The people in Colombia are very friendly and welcoming."'},
      {en:'hardworking',es:'trabajador/a / dedicado/a',example:'"She is hardworking and always finishes her tasks on time."'},
    ]
  },
  {
    id:'food_drink', title:'Comida y bebida', icon:'🍽️', count:20,
    words:[
      {en:'bread',es:'pan',example:'"I have toast and bread for breakfast every morning."'},
      {en:'rice',es:'arroz',example:'"Rice is very popular in Colombia and all of South America."'},
      {en:'chicken',es:'pollo',example:'"She cooks chicken with vegetables every Sunday."'},
      {en:'fish',es:'pescado',example:'"I love fish. We eat it at least twice a week."'},
      {en:'eggs',es:'huevos',example:'"I have scrambled eggs for breakfast on Saturdays."'},
      {en:'fruit',es:'fruta',example:'"I eat fruit every day to stay healthy."'},
      {en:'vegetables',es:'verduras / vegetales',example:'"The doctor says I should eat more vegetables."'},
      {en:'water',es:'agua',example:'"You should drink eight glasses of water a day."'},
      {en:'coffee',es:'café',example:'"I always drink a cup of black coffee in the morning."'},
      {en:'tea',es:'té',example:'"British people love drinking tea. They drink it all day!"'},
      {en:'milk',es:'leche',example:'"She adds milk to her coffee every morning."'},
      {en:'juice',es:'zumo / jugo',example:'"I drink orange juice every morning. It\'s delicious."'},
      {en:'soup',es:'sopa',example:'"We always eat hot soup when it\'s cold outside."'},
      {en:'salad',es:'ensalada',example:'"I eat a fresh salad for lunch every day."'},
      {en:'pasta',es:'pasta',example:'"Pasta is quick and easy to cook. I love it!"'},
      {en:'chocolate',es:'chocolate',example:'"I love dark chocolate. It\'s my favourite treat."'},
      {en:'sandwich',es:'sándwich / bocadillo',example:'"I have a cheese sandwich for lunch at work."'},
      {en:'cake',es:'pastel / torta',example:'"She made a delicious chocolate cake for my birthday."'},
      {en:'meat',es:'carne',example:'"He doesn\'t eat meat. He is a vegetarian."'},
      {en:'sugar',es:'azúcar',example:'"I don\'t put sugar in my coffee. I prefer it bitter."'},
    ]
  },
  {
    id:'body_health', title:'El cuerpo y la salud', icon:'🏥', count:20,
    words:[
      {en:'head',es:'cabeza',example:'"I have a terrible headache today."'},
      {en:'face',es:'cara / rostro',example:'"She has a beautiful face and kind eyes."'},
      {en:'eye',es:'ojo',example:'"She has green eyes. They are very beautiful."'},
      {en:'ear',es:'oreja / oído',example:'"I can\'t hear well. I have a problem with my ear."'},
      {en:'nose',es:'nariz',example:'"He has a cold. His nose is red."'},
      {en:'mouth',es:'boca',example:'"Open your mouth, please. The dentist needs to look inside."'},
      {en:'tooth / teeth',es:'diente / dientes',example:'"You should brush your teeth twice a day."'},
      {en:'neck',es:'cuello',example:'"My neck hurts after sitting at the computer all day."'},
      {en:'shoulder',es:'hombro',example:'"She carries her heavy bag on one shoulder."'},
      {en:'arm',es:'brazo',example:'"He broke his arm playing football last week."'},
      {en:'hand',es:'mano',example:'"She shook my hand when we met for the first time."'},
      {en:'leg',es:'pierna',example:'"My legs are sore after running this morning."'},
      {en:'foot / feet',es:'pie / pies',example:'"My feet hurt after walking all day."'},
      {en:'stomach',es:'estómago / barriga',example:'"I have a stomachache. I think I ate something bad."'},
      {en:'back',es:'espalda',example:'"She has back pain from sitting at her desk all day."'},
      {en:'headache',es:'dolor de cabeza',example:'"I have a terrible headache. I need some paracetamol."'},
      {en:'cold',es:'resfriado',example:'"I have a cold. I\'m sneezing and my nose is running."'},
      {en:'fever',es:'fiebre',example:'"The child has a high fever. We need to call the doctor."'},
      {en:'tired',es:'cansado/a',example:'"I\'m very tired. I only slept four hours last night."'},
      {en:'healthy',es:'sano/a / saludable',example:'"She is very healthy. She exercises every day and eats well."'},
    ]
  },
  {
    id:'transport_travel', title:'Transporte y viajes', icon:'✈️', count:18,
    words:[
      {en:'car',es:'coche / auto / carro',example:'"He drives his car to work every day."'},
      {en:'bus',es:'autobús / bus',example:'"I take the bus to school. It\'s cheaper than a taxi."'},
      {en:'train',es:'tren',example:'"The train to Bogotá leaves at eight o\'clock."'},
      {en:'plane / aeroplane',es:'avión',example:'"We took a plane to London. The flight was five hours."'},
      {en:'underground / metro / tube',es:'metro',example:'"The London Underground is called the Tube."'},
      {en:'taxi',es:'taxi',example:'"We took a taxi from the airport to the hotel."'},
      {en:'bicycle / bike',es:'bicicleta',example:'"She rides her bike to university every morning."'},
      {en:'motorbike',es:'motocicleta / moto',example:'"He has a red motorbike. He loves riding it."'},
      {en:'station',es:'estación',example:'"The bus station is next to the market in the city centre."'},
      {en:'airport',es:'aeropuerto',example:'"We arrived at the airport two hours before the flight."'},
      {en:'ticket',es:'billete / tiquete',example:'"I bought two return tickets for the train."'},
      {en:'passport',es:'pasaporte',example:'"Don\'t forget your passport. You can\'t travel without it."'},
      {en:'luggage / suitcase',es:'equipaje / maleta',example:'"My suitcase is very heavy. I packed too many clothes."'},
      {en:'hotel',es:'hotel',example:'"We stayed at a five-star hotel near the beach."'},
      {en:'journey / trip',es:'viaje / trayecto',example:'"The journey from Cúcuta to Bogotá takes about eight hours."'},
      {en:'on foot',es:'a pie / caminando',example:'"The supermarket is close. We can go on foot."'},
      {en:'arrive',es:'llegar',example:'"What time does the flight arrive in Madrid?"'},
      {en:'depart / leave',es:'salir / partir',example:'"The train departs from platform 3 at 10:15."'},
    ]
  },
];